//! End-to-end sandwich attack test against the AMM program via LiteSVM.
//!
//! Spins up an in-process SVM, loads the compiled SBF artifact from
//! `target/deploy/amm.so`, initializes a pool with 0.30% fee, seeds liquidity
//! and executes a frontrun -> victim -> backrun sandwich. Each on-chain swap
//! output is cross-checked against the off-chain `amm-math` implementation
//! (Uniswap V2 constant-product, Adams et al. 2020, §3.1.1).

use std::path::PathBuf;

use amm_math::constant_product::compute_swap;
use anchor_lang::solana_program::system_instruction;
use anchor_lang::{AccountDeserialize, InstructionData, ToAccountMetas};
use litesvm::LiteSVM;
use solana_keypair::Keypair;
use solana_message::Message;
use solana_pubkey::Pubkey;
use solana_sdk::instruction::Instruction;
use solana_signer::Signer;
use solana_transaction::Transaction;

// SPL Token program id + instruction builders (re-exported through anchor-spl).
use anchor_spl::token::spl_token as spl_token_iface;
use anchor_spl::token::ID as TOKEN_PROGRAM_ID;

// Anchor program under test — re-import the instruction & accounts modules
// generated by #[program] / #[derive(Accounts)].
use amm::accounts as amm_accounts;
use amm::instruction as amm_instruction;

/// Constants mirroring `programs/amm/src/constants.rs`.
const POOL_SEED: &[u8] = b"pool";
const POOL_AUTHORITY_SEED: &[u8] = b"pool_authority";
const LP_MINT_SEED: &[u8] = b"lp_mint";
const VAULT_A_SEED: &[u8] = b"vault_a";
const VAULT_B_SEED: &[u8] = b"vault_b";

const SPL_MINT_LEN: usize = 82;
const SPL_ACCOUNT_LEN: usize = 165;

const LAMPORTS_PER_SOL: u64 = 1_000_000_000;

/// AMM program id declared in `programs/amm/src/lib.rs`.
fn amm_program_id() -> Pubkey {
    Pubkey::from_str_const("DEwKoXtDPgme9dVdKVj7eLta7mzFDyGxA9DCssTVEiRz")
}

fn amm_so_path() -> PathBuf {
    // `CARGO_MANIFEST_DIR` for this test crate = programs/amm
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.pop(); // -> programs
    p.pop(); // -> repo root
    p.push("target");
    p.push("deploy");
    p.push("amm.so");
    p
}

/// Convenience: sign + send + unwrap on success.
fn send(svm: &mut LiteSVM, payer: &Keypair, extra_signers: &[&Keypair], ixs: &[Instruction]) {
    let blockhash = svm.latest_blockhash();
    let msg = Message::new_with_blockhash(ixs, Some(&payer.pubkey()), &blockhash);
    let mut signers: Vec<&Keypair> = Vec::with_capacity(1 + extra_signers.len());
    signers.push(payer);
    signers.extend_from_slice(extra_signers);
    let tx = Transaction::new(&signers, msg, blockhash);
    let res = svm.send_transaction(tx);
    if let Err(e) = res {
        panic!("tx failed: {e:?}");
    }
}

fn rent_for(svm: &LiteSVM, data_len: usize) -> u64 {
    svm.minimum_balance_for_rent_exemption(data_len)
}

/// Create a new SPL mint (0 decimals, payer is mint authority, no freeze).
fn create_mint(svm: &mut LiteSVM, payer: &Keypair, decimals: u8) -> Keypair {
    let mint = Keypair::new();
    let create_ix = system_instruction::create_account(
        &payer.pubkey(),
        &mint.pubkey(),
        rent_for(svm, SPL_MINT_LEN),
        SPL_MINT_LEN as u64,
        &TOKEN_PROGRAM_ID,
    );
    let init_ix = spl_token_iface::instruction::initialize_mint2(
        &TOKEN_PROGRAM_ID,
        &mint.pubkey(),
        &payer.pubkey(),
        None,
        decimals,
    )
    .unwrap();
    send(svm, payer, &[&mint], &[create_ix, init_ix]);
    mint
}

/// Create an SPL token account owned by `owner`, for `mint`. Returns its pubkey.
fn create_token_account(
    svm: &mut LiteSVM,
    payer: &Keypair,
    mint: &Pubkey,
    owner: &Pubkey,
) -> Keypair {
    let acc = Keypair::new();
    let create_ix = system_instruction::create_account(
        &payer.pubkey(),
        &acc.pubkey(),
        rent_for(svm, SPL_ACCOUNT_LEN),
        SPL_ACCOUNT_LEN as u64,
        &TOKEN_PROGRAM_ID,
    );
    let init_ix = spl_token_iface::instruction::initialize_account3(
        &TOKEN_PROGRAM_ID,
        &acc.pubkey(),
        mint,
        owner,
    )
    .unwrap();
    send(svm, payer, &[&acc], &[create_ix, init_ix]);
    acc
}

fn mint_to(
    svm: &mut LiteSVM,
    payer: &Keypair,
    mint: &Pubkey,
    dest: &Pubkey,
    authority: &Keypair,
    amount: u64,
) {
    let ix = spl_token_iface::instruction::mint_to(
        &TOKEN_PROGRAM_ID,
        mint,
        dest,
        &authority.pubkey(),
        &[],
        amount,
    )
    .unwrap();
    send(svm, payer, &[authority], &[ix]);
}

/// Read SPL token account amount from its raw 165-byte data.
/// Layout: mint(32) | owner(32) | amount(u64 LE) | ...
fn token_balance(svm: &LiteSVM, account: &Pubkey) -> u64 {
    let acc = svm.get_account(account).expect("token account missing");
    let amt = &acc.data[64..72];
    u64::from_le_bytes(amt.try_into().unwrap())
}

/// Load on-chain Pool reserves.
fn read_pool_reserves(svm: &LiteSVM, pool: &Pubkey) -> (u64, u64) {
    let acc = svm.get_account(pool).expect("pool account missing");
    let mut slice: &[u8] = &acc.data;
    let pool_state = amm::state::Pool::try_deserialize(&mut slice).expect("pool deser");
    (pool_state.reserve_a, pool_state.reserve_b)
}

struct PoolPdas {
    pool: Pubkey,
    pool_authority: Pubkey,
    lp_mint: Pubkey,
    vault_a: Pubkey,
    vault_b: Pubkey,
}

fn derive_pool_pdas(program_id: &Pubkey, mint_a: &Pubkey, mint_b: &Pubkey) -> PoolPdas {
    let (pool, _) =
        Pubkey::find_program_address(&[POOL_SEED, mint_a.as_ref(), mint_b.as_ref()], program_id);
    let (pool_authority, _) =
        Pubkey::find_program_address(&[POOL_AUTHORITY_SEED, pool.as_ref()], program_id);
    let (lp_mint, _) = Pubkey::find_program_address(&[LP_MINT_SEED, pool.as_ref()], program_id);
    let (vault_a, _) = Pubkey::find_program_address(&[VAULT_A_SEED, pool.as_ref()], program_id);
    let (vault_b, _) = Pubkey::find_program_address(&[VAULT_B_SEED, pool.as_ref()], program_id);
    PoolPdas {
        pool,
        pool_authority,
        lp_mint,
        vault_a,
        vault_b,
    }
}

/// Assert two amounts differ by at most `tol` units.
fn assert_close(got: u64, want: u64, tol: u64, label: &str) {
    let diff = if got > want { got - want } else { want - got };
    assert!(
        diff <= tol,
        "{label}: on-chain {got} vs expected {want} (diff {diff} > tol {tol})"
    );
}

#[test]
fn sandwich_e2e() {
    // --- Setup SVM + load AMM program ---
    // NOTE: `LiteSVM::new()` uses `FeatureSet::all_enabled()` which activates
    // the `replace_spl_token_with_p_token` feature and loads the pinocchio
    // token implementation (`pinocchio_token_program.so`) at the SPL Token
    // address. That build rejects our raw `InitializeMint2` (custom error 4,
    // "owner does not match"). Constructing with `FeatureSet::default()`
    // (all-disabled) forces the classic `spl_token-3.5.0.so` to load, which
    // accepts our instructions.
    let mut svm = LiteSVM::default()
        .with_builtins()
        .with_lamports(1_000_000u64.wrapping_mul(LAMPORTS_PER_SOL))
        .with_sysvars()
        .with_feature_accounts()
        .with_default_programs()
        .with_sigverify(true)
        .with_blockhash_check(true);
    let program_id = amm_program_id();
    svm.add_program_from_file(program_id, amm_so_path())
        .expect("load amm.so — did you run `cargo build-sbf -p amm`?");

    // --- Actors ---
    let payer = Keypair::new();
    svm.airdrop(&payer.pubkey(), 10 * LAMPORTS_PER_SOL).unwrap();
    let attacker = Keypair::new();
    svm.airdrop(&attacker.pubkey(), 10 * LAMPORTS_PER_SOL)
        .unwrap();
    let victim = Keypair::new();
    svm.airdrop(&victim.pubkey(), 10 * LAMPORTS_PER_SOL)
        .unwrap();

    // --- Two mints, ordered so mint_a < mint_b (program enforces). ---
    let (mint_a_kp, mint_b_kp) = loop {
        let m1 = create_mint(&mut svm, &payer, 0);
        let m2 = create_mint(&mut svm, &payer, 0);
        if m1.pubkey() < m2.pubkey() {
            break (m1, m2);
        } else if m2.pubkey() < m1.pubkey() {
            break (m2, m1);
        }
        // astronomically unlikely equality — retry
    };
    let mint_a = mint_a_kp.pubkey();
    let mint_b = mint_b_kp.pubkey();

    // --- Token accounts for payer / attacker / victim ---
    let payer_a = create_token_account(&mut svm, &payer, &mint_a, &payer.pubkey()).pubkey();
    let payer_b = create_token_account(&mut svm, &payer, &mint_b, &payer.pubkey()).pubkey();
    let attacker_a = create_token_account(&mut svm, &payer, &mint_a, &attacker.pubkey()).pubkey();
    let attacker_b = create_token_account(&mut svm, &payer, &mint_b, &attacker.pubkey()).pubkey();
    let victim_a = create_token_account(&mut svm, &payer, &mint_a, &victim.pubkey()).pubkey();
    let victim_b = create_token_account(&mut svm, &payer, &mint_b, &victim.pubkey()).pubkey();

    // --- Seed balances ---
    // Payer provides initial liquidity (1M A + 4M B).
    let payer_a_seed: u64 = 1_000_000;
    let payer_b_seed: u64 = 4_000_000;
    mint_to(&mut svm, &payer, &mint_a, &payer_a, &payer, payer_a_seed);
    mint_to(&mut svm, &payer, &mint_b, &payer_b, &payer, payer_b_seed);
    // Attacker & victim get some A to trade.
    let attacker_initial_a: u64 = 50_000;
    let victim_initial_a: u64 = 10_000;
    mint_to(
        &mut svm,
        &payer,
        &mint_a,
        &attacker_a,
        &payer,
        attacker_initial_a,
    );
    mint_to(
        &mut svm,
        &payer,
        &mint_a,
        &victim_a,
        &payer,
        victim_initial_a,
    );

    // --- Derive pool PDAs ---
    let pdas = derive_pool_pdas(&program_id, &mint_a, &mint_b);

    // --- Payer LP token account (regular, not PDA) for user_lp_token. ---
    // We need the lp_mint to exist first → that happens during initialize_pool.
    // So we'll create this account after init. pool_authority_lp_token is also
    // a regular SPL account owned by the pool_authority PDA.

    // --- Initialize pool (fee_bps = 30) ---
    let init_accounts = amm_accounts::InitializePool {
        payer: payer.pubkey(),
        pool: pdas.pool,
        pool_authority: pdas.pool_authority,
        token_a_mint: mint_a,
        token_b_mint: mint_b,
        token_a_vault: pdas.vault_a,
        token_b_vault: pdas.vault_b,
        lp_mint: pdas.lp_mint,
        token_program: TOKEN_PROGRAM_ID,
        system_program: anchor_lang::solana_program::system_program::ID,
    }
    .to_account_metas(None);
    let init_ix = Instruction {
        program_id,
        accounts: init_accounts,
        data: amm_instruction::InitializePool { fee_bps: 30 }.data(),
    };
    send(&mut svm, &payer, &[], &[init_ix]);

    // --- Create LP token accounts (payer's + pool_authority's dead account). ---
    let payer_lp = create_token_account(&mut svm, &payer, &pdas.lp_mint, &payer.pubkey()).pubkey();
    let pool_authority_lp =
        create_token_account(&mut svm, &payer, &pdas.lp_mint, &pdas.pool_authority).pubkey();

    // --- Add liquidity: 1M A + 4M B ---
    let liq_a = payer_a_seed;
    let liq_b = payer_b_seed;
    let add_liq_accounts = amm_accounts::AddLiquidity {
        user: payer.pubkey(),
        pool: pdas.pool,
        pool_authority: pdas.pool_authority,
        token_a_mint: mint_a,
        token_b_mint: mint_b,
        token_a_vault: pdas.vault_a,
        token_b_vault: pdas.vault_b,
        lp_mint: pdas.lp_mint,
        user_lp_token: payer_lp,
        pool_authority_lp_token: pool_authority_lp,
        user_token_a: payer_a,
        user_token_b: payer_b,
        token_program: TOKEN_PROGRAM_ID,
    }
    .to_account_metas(None);
    let add_liq_ix = Instruction {
        program_id,
        accounts: add_liq_accounts,
        data: amm_instruction::AddLiquidity {
            amount_a: liq_a,
            amount_b: liq_b,
            min_lp_out: 0,
        }
        .data(),
    };
    send(&mut svm, &payer, &[], &[add_liq_ix]);

    let (r_a_0, r_b_0) = read_pool_reserves(&svm, &pdas.pool);
    assert_eq!(r_a_0, liq_a);
    assert_eq!(r_b_0, liq_b);

    // Helper to build a swap instruction (A->B or B->A).
    let build_swap_ix = |user: &Pubkey,
                         user_token_in: &Pubkey,
                         user_token_out: &Pubkey,
                         mint_in: &Pubkey,
                         mint_out: &Pubkey,
                         vault_in: &Pubkey,
                         vault_out: &Pubkey,
                         amount_in: u64,
                         min_out: u64|
     -> Instruction {
        let accounts = amm_accounts::Swap {
            user: *user,
            pool: pdas.pool,
            pool_authority: pdas.pool_authority,
            mint_in: *mint_in,
            mint_out: *mint_out,
            vault_in: *vault_in,
            vault_out: *vault_out,
            user_token_in: *user_token_in,
            user_token_out: *user_token_out,
            token_program: TOKEN_PROGRAM_ID,
        }
        .to_account_metas(None);
        Instruction {
            program_id,
            accounts,
            data: amm_instruction::Swap {
                amount_in,
                min_amount_out: min_out,
            }
            .data(),
        }
    };

    // --- Sandwich step 1: attacker frontrun (A -> B) ---
    // Pick V_f heuristically = 20_000 A (40% of attacker stack, enough to move price).
    let frontrun_in: u64 = 20_000;
    let expected_fr =
        compute_swap(frontrun_in as u128, r_a_0 as u128, r_b_0 as u128, 30).expect("fr math");
    let fr_ix = build_swap_ix(
        &attacker.pubkey(),
        &attacker_a,
        &attacker_b,
        &mint_a,
        &mint_b,
        &pdas.vault_a,
        &pdas.vault_b,
        frontrun_in,
        0,
    );
    send(&mut svm, &attacker, &[], &[fr_ix]);

    let attacker_b_after_fr = token_balance(&svm, &attacker_b);
    assert_close(
        attacker_b_after_fr,
        expected_fr.amount_out as u64,
        1,
        "frontrun out",
    );
    let (r_a_1, r_b_1) = read_pool_reserves(&svm, &pdas.pool);
    assert_eq!(r_a_1, expected_fr.new_reserve_in as u64);
    assert_eq!(r_b_1, expected_fr.new_reserve_out as u64);

    // --- Sandwich step 2: victim swap 10_000 A -> B (worse price now) ---
    let victim_in: u64 = victim_initial_a;
    let expected_vic =
        compute_swap(victim_in as u128, r_a_1 as u128, r_b_1 as u128, 30).expect("vic math");
    let vic_ix = build_swap_ix(
        &victim.pubkey(),
        &victim_a,
        &victim_b,
        &mint_a,
        &mint_b,
        &pdas.vault_a,
        &pdas.vault_b,
        victim_in,
        0,
    );
    send(&mut svm, &victim, &[], &[vic_ix]);

    let victim_b_after = token_balance(&svm, &victim_b);
    assert_close(
        victim_b_after,
        expected_vic.amount_out as u64,
        1,
        "victim out",
    );
    let (r_a_2, r_b_2) = read_pool_reserves(&svm, &pdas.pool);
    assert_eq!(r_a_2, expected_vic.new_reserve_in as u64);
    assert_eq!(r_b_2, expected_vic.new_reserve_out as u64);

    // --- Sandwich step 3: attacker backrun (all B -> A) ---
    let backrun_in: u64 = attacker_b_after_fr;
    // Backrun direction B -> A: input reserve = r_b_2, output reserve = r_a_2.
    let expected_br =
        compute_swap(backrun_in as u128, r_b_2 as u128, r_a_2 as u128, 30).expect("br math");
    let br_ix = build_swap_ix(
        &attacker.pubkey(),
        &attacker_b,
        &attacker_a,
        &mint_b,
        &mint_a,
        &pdas.vault_b,
        &pdas.vault_a,
        backrun_in,
        0,
    );
    send(&mut svm, &attacker, &[], &[br_ix]);

    let attacker_a_final = token_balance(&svm, &attacker_a);
    let attacker_b_final = token_balance(&svm, &attacker_b);
    // Attacker swapped all their B -> A, so expected A balance is
    // (initial - frontrun_in) + expected_br.amount_out.
    let expected_attacker_a_final =
        attacker_initial_a - frontrun_in + expected_br.amount_out as u64;
    assert_close(
        attacker_a_final,
        expected_attacker_a_final,
        1,
        "attacker final A",
    );
    assert_eq!(
        attacker_b_final, 0,
        "attacker should have drained B on backrun"
    );

    // --- Gross profit assertion: attacker ended with more A than they started ---
    assert!(
        attacker_a_final > attacker_initial_a,
        "sandwich was not profitable: started {} A, ended {} A",
        attacker_initial_a,
        attacker_a_final
    );
    let gross_profit = attacker_a_final - attacker_initial_a;
    println!(
        "sandwich gross profit: {gross_profit} A (in: {frontrun_in}+0 / out: {} via backrun)",
        expected_br.amount_out
    );
}
